version: "3"

silent: true

tasks:
    build:
        cmds:
            - |
                echo "// SPDX-License-Identifier: Apache-2.0
                public enum VersionInfo {
                    public static let version = \"$(git describe --tags $(git rev-list --tags --max-count=1))-dev\"
                }" > Sources/Hiero/Version.swift
            - swift build

    format:
        deps: [swift-format:install]
        cmds:
            - .build/swift-format/swift-format --configuration .swift-format.json --recursive --in-place --parallel Sources/ Tests/ Examples/ Package.swift

    lint:
        deps: [swift-format:install]
        cmds:
            - cmd: swiftlint --quiet
              ignore_error: true
            - .build/swift-format/swift-format lint --configuration .swift-format.json --recursive --parallel Sources/ Tests/ Examples/ Package.swift

    swift-format:install:
        desc: "Install swift-format 600.0.0 (matches CI)"
        vars:
            SWIFT_FORMAT_VERSION: "600.0.0"
        status:
            - test -f .build/swift-format/swift-format
        cmds:
            - rm -rf .build/swift-format-src .build/swift-format
            - git clone --depth=1 --branch {{.SWIFT_FORMAT_VERSION}} https://github.com/apple/swift-format.git .build/swift-format-src
            - cd .build/swift-format-src && swift build -c release
            - mkdir -p .build/swift-format
            - cp .build/swift-format-src/.build/release/swift-format .build/swift-format/
            - rm -rf .build/swift-format-src
            - echo "Installed swift-format {{.SWIFT_FORMAT_VERSION}}"

    package:
        desc: "Build package"
        cmds:
            - |
                echo "// SPDX-License-Identifier: Apache-2.0
                public enum VersionInfo {
                    public static let version = \"$(git describe --tags)\"
                }" > Sources/Hiero/Version.swift
            - swift build -c release

    example:
        desc: "Run example"
        cmds:
            - swift run {{.name}}Example

    submodule:fetch:
        desc: "Fetch a specific version of the submodule, or else the latest version. E.g. task submodule:fetch proto=vX.Y.Z"
        dir: protobufs
        vars:
            latest_tag:
                sh: >
                    git tag -l --sort=version:refname | 
                    grep -v 'alpha\|beta\|rc' |
                    tail -1
            proto: "{{.proto | default .latest_tag}}"
            current_version:
                sh: git describe --tags
        cmds:
            - echo "Protobuf version set to {{.proto}}"
            - |
                if [ "{{.current_version}}" = "{{.proto}}" ]; then
                    echo "Warning: Already at version {{.proto}}, skipping update"
                    exit 0
                fi
            - git fetch origin
            - git checkout {{.proto}}
            - git show-ref --verify -q refs/heads/{{.proto}} && git pull origin || exit 0
            - cd ..
            - task: submodule:generate
            - task: build
            - echo "Successfully updated protobufs to {{.proto}}"

    submodule:generate:
        desc: "Generate the swift files from the protobufs"
        dir: Sources/HieroProtobufs
        cmds:
            - cmd: python3 update_protos.py
            - cmd: python3 sync_status_codes.py
            - cmd: task format

