// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: crypto_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

///*
/// # Crypto Service
/// A service defining transactions and queries related to accounts.
///
/// This includes transactions for HBAR transfers and balance queries as well as
/// transactions to manage "allowances" which permit a third party to spend a
/// portion of the HBAR balance in an account.<br/>
/// Basic account, record, and receipt queries are also defined in this service.
///
/// Transactions and queries relating to tokens _other than HBAR_ are defined
/// in the Token Service.
///
/// ### Keywords
/// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
/// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
/// document are to be interpreted as described in
/// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
/// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// This file contained no messages, enums, or extensions.
