//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: util_service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


///*
/// The Utility Service provides a pseudo-random number generator.
///
/// The single gRPC call defined for this service simply reports a single
/// pseudo-random number in the transaction record. That value may either
/// be a 32-bit integer within a requested range, or a 384-bit byte array.
///
/// ### Block Stream Effects
/// The requested value is reported exclusively in a `UtilPrngOutput` message.
///
/// Usage: instantiate `Proto_UtilServiceClient`, then call methods of this protocol to make API calls.
public protocol Proto_UtilServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? { get }

  func prng(
    _ request: Proto_Transaction,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_Transaction, Proto_TransactionResponse>
}

extension Proto_UtilServiceClientProtocol {
  public var serviceName: String {
    return "proto.UtilService"
  }

  ///*
  /// Generate a pseudo-random value.
  /// <p>
  /// The request body MUST be a
  /// [UtilPrngTransactionBody](#proto.UtilPrngTransactionBody)
  ///
  /// - Parameters:
  ///   - request: Request to send to prng.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func prng(
    _ request: Proto_Transaction,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_Transaction, Proto_TransactionResponse> {
    return self.makeUnaryCall(
      path: Proto_UtilServiceClientMetadata.Methods.prng.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeprngInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Proto_UtilServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Proto_UtilServiceNIOClient")
public final class Proto_UtilServiceClient: Proto_UtilServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the proto.UtilService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Proto_UtilServiceNIOClient: Proto_UtilServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the proto.UtilService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

///*
/// The Utility Service provides a pseudo-random number generator.
///
/// The single gRPC call defined for this service simply reports a single
/// pseudo-random number in the transaction record. That value may either
/// be a 32-bit integer within a requested range, or a 384-bit byte array.
///
/// ### Block Stream Effects
/// The requested value is reported exclusively in a `UtilPrngOutput` message.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Proto_UtilServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? { get }

  func makePrngCall(
    _ request: Proto_Transaction,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Proto_Transaction, Proto_TransactionResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Proto_UtilServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Proto_UtilServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makePrngCall(
    _ request: Proto_Transaction,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Proto_Transaction, Proto_TransactionResponse> {
    return self.makeAsyncUnaryCall(
      path: Proto_UtilServiceClientMetadata.Methods.prng.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeprngInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Proto_UtilServiceAsyncClientProtocol {
  public func prng(
    _ request: Proto_Transaction,
    callOptions: CallOptions? = nil
  ) async throws -> Proto_TransactionResponse {
    return try await self.performAsyncUnaryCall(
      path: Proto_UtilServiceClientMetadata.Methods.prng.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeprngInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Proto_UtilServiceAsyncClient: Proto_UtilServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Proto_UtilServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'prng'.
  func makeprngInterceptors() -> [ClientInterceptor<Proto_Transaction, Proto_TransactionResponse>]
}

public enum Proto_UtilServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "UtilService",
    fullName: "proto.UtilService",
    methods: [
      Proto_UtilServiceClientMetadata.Methods.prng,
    ]
  )

  public enum Methods {
    public static let prng = GRPCMethodDescriptor(
      name: "prng",
      path: "/proto.UtilService/prng",
      type: GRPCCallType.unary
    )
  }
}

///*
/// The Utility Service provides a pseudo-random number generator.
///
/// The single gRPC call defined for this service simply reports a single
/// pseudo-random number in the transaction record. That value may either
/// be a 32-bit integer within a requested range, or a 384-bit byte array.
///
/// ### Block Stream Effects
/// The requested value is reported exclusively in a `UtilPrngOutput` message.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Proto_UtilServiceProvider: CallHandlerProvider {
  var interceptors: Proto_UtilServiceServerInterceptorFactoryProtocol? { get }

  ///*
  /// Generate a pseudo-random value.
  /// <p>
  /// The request body MUST be a
  /// [UtilPrngTransactionBody](#proto.UtilPrngTransactionBody)
  func prng(request: Proto_Transaction, context: StatusOnlyCallContext) -> EventLoopFuture<Proto_TransactionResponse>
}

extension Proto_UtilServiceProvider {
  public var serviceName: Substring {
    return Proto_UtilServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "prng":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Proto_Transaction>(),
        responseSerializer: ProtobufSerializer<Proto_TransactionResponse>(),
        interceptors: self.interceptors?.makeprngInterceptors() ?? [],
        userFunction: self.prng(request:context:)
      )

    default:
      return nil
    }
  }
}

///*
/// The Utility Service provides a pseudo-random number generator.
///
/// The single gRPC call defined for this service simply reports a single
/// pseudo-random number in the transaction record. That value may either
/// be a 32-bit integer within a requested range, or a 384-bit byte array.
///
/// ### Block Stream Effects
/// The requested value is reported exclusively in a `UtilPrngOutput` message.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Proto_UtilServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Proto_UtilServiceServerInterceptorFactoryProtocol? { get }

  ///*
  /// Generate a pseudo-random value.
  /// <p>
  /// The request body MUST be a
  /// [UtilPrngTransactionBody](#proto.UtilPrngTransactionBody)
  func prng(
    request: Proto_Transaction,
    context: GRPCAsyncServerCallContext
  ) async throws -> Proto_TransactionResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Proto_UtilServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Proto_UtilServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Proto_UtilServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Proto_UtilServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "prng":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Proto_Transaction>(),
        responseSerializer: ProtobufSerializer<Proto_TransactionResponse>(),
        interceptors: self.interceptors?.makeprngInterceptors() ?? [],
        wrapping: { try await self.prng(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Proto_UtilServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'prng'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeprngInterceptors() -> [ServerInterceptor<Proto_Transaction, Proto_TransactionResponse>]
}

public enum Proto_UtilServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "UtilService",
    fullName: "proto.UtilService",
    methods: [
      Proto_UtilServiceServerMetadata.Methods.prng,
    ]
  )

  public enum Methods {
    public static let prng = GRPCMethodDescriptor(
      name: "prng",
      path: "/proto.UtilService/prng",
      type: GRPCCallType.unary
    )
  }
}
