name: Good First Issue Template
description: Create a Good First Issue for new contributors (Swift)
title: "[Good First Issue]: "
labels: ["Good First Issue"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort. If this is your first open-source contribution, welcome!

        This template is designed to help you create a **Good First Issue (GFI)** —
        a small, well-scoped task that helps new contributors learn the
        **Hiero Swift SDK** codebase and workflow.

        > Maintainers can read more about:
        > - [Good First Issues](https://github.com/hiero-ledger/hiero-sdk-swift/blob/main/docs/maintainers/guidelines-good-first-issues.md)
        > - [Good First Issue Candidates](https://github.com/hiero-ledger/hiero-sdk-swift/blob/main/docs/maintainers/guidelines-good-first-issue-candidates.md)
        ---

  - type: textarea
    id: intro
    attributes:
      label: 🆕🐥 First-Time Friendly
      description: Who is this issue for?
      value: |
        This issue is especially welcoming for people who are new to contributing to the **Hiero Swift SDK**.

        We know that opening your first pull request can feel like a big step.  
        Issues labeled **Good First Issue** are designed to make that experience easier, clearer, and more comfortable.

        No prior knowledge of Hiero, Hedera, or distributed ledger technology is required.  
        Just a basic familiarity with Swift and Git is more than enough to get started.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 📋 About Good First Issues
        >
        > Good First Issues are designed to make getting started as smooth and stress-free
        > as possible.
        >
        > They usually focus on:
        > - Small, clearly scoped changes  
        > - Straightforward updates to existing code or docs  
        > - Simple refactors or clarity improvements  
        >
        > Other kinds of contributions — like larger features, deeper technical changes,
        > or design-focused work — are just as valuable and often use the beginner, intermediate, or advanced labels.

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the Issue
      description: |
        Describe the issue in a way that's easy for new contributors to understand.

        Aim to keep the explanation clear and accessible for people who are new to the codebase and Hiero.
        Links to relevant files or examples are always helpful.
      value: |
        Edit here. An example is provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ## 👾 Description of the Issue — Example (Swift)

        The file:

        ```Sources/Hiero/TokenAssociateTransaction.swift```

        contains several methods that are part of the
        `TokenAssociateTransaction` implementation.

        Some of these methods lack brief comments explaining their purpose,
        which can make the file harder to understand for new contributors
        who are unfamiliar with the SDK.

        For example, methods like `execute()` and `toProtobuf()` are
        correctly implemented, but their intent is not immediately obvious
        without reading surrounding code.

        The behavior is correct, but adding small, clear comments would
        make the file easier to read and maintain.

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        Describe the solution at a high level.
        Focus on what should be done, keeping the solution clear and straightforward.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ## 💡 Proposed Solution — Example

        Add short, descriptive comments above selected methods in
        `TokenAssociateTransaction.swift` explaining what each method does
        and when it is used.

        The changes should:
        - Not modify any existing logic
        - Not change behavior or public APIs
        - Be limited to comments only
        - Improve readability for new contributors

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps (End-to-End)
      description: |
        Please write out the end-to-end process for completing this issue from start to finish.

        The steps should clearly describe:
        - Where to begin  
        - Which files to open  
        - What to change  
        - How to make the change (e.g. what code to add, remove, or update)  
        - What the final result should look like  

        Clear, connected instructions help make the contribution experience smoother
        and more enjoyable for everyone.
      value: |
        Edit here. An example is provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ### 👩‍💻 Implementation — Example

        To complete this change:

        - [ ] Open `Sources/Hiero/TokenAssociateTransaction.swift`
        - [ ] Locate the following methods that need comments:
          - `execute()`
          - `toProtobuf()`
        - [ ] Add **concise, single-line comments** above each method that explain:
          - What the method does
          - When it is used in the transaction flow

        **Comment guidelines:**
        - Use standard Swift `///` documentation comments
        - Limit each comment to **one line (≈80 characters max)**
        - Example:
          ```swift
          /// Builds and submits the token association request to the network.
          ```

        - [ ] Run existing tests or CI locally **if already set up**  
              (CI will also run automatically when you open a pull request)

        This change should only affect comments and readability.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Checklist required for completing this issue
      value: |
        To merge a pull request for this issue:

        - [ ] **Scope:** Changes are limited to this issue
        - [ ] **Behavior:** No SDK behavior or public API changes
        - [ ] **Tests:** Existing CI checks pass
        - [ ] **Review:** All code review feedback addressed
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-Step Contribution Guide
      description: Contribution workflow for new contributors
      value: |
        To help your first contribution go as smoothly as possible, we recommend following these steps:

        - [ ] Comment `/assign` to request the issue
        - [ ] Wait for assignment
        - [ ] Fork the repository and create a branch
        - [ ] Set up the project by following the instructions in `README.md`
        - [ ] Make the requested changes
        - [ ] Sign each commit using `-s -S`
        - [ ] Push your branch and open a pull request

        Read [Workflow Guide](docs/training/workflow.md) for step-by-step workflow guidance.  
        Read [README.md](README.md) for setup instructions.

        ❗ Pull requests **cannot be merged** without `S` and `s` signed commits.  
        See the [Signing Guide](docs/training/signing.md).
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Information
      description: Extra context or resources for contributors
      value: |
        If you need help, reach out to the @hiero-ledger/hiero-sdk-good-first-issue-support team.

        You can also join our community on Discord:
        [Hiero Discord](https://discord.com/channels/905194001349627914/1337424839761465364)

        Maintainers are happy to help first-time contributors succeed!
